### ISSUE TITLE
Outrun 2006 - Extract audio files

### ISSUE THREAD

**Issue by thegreatprophetzarquon** [ksdomino/OR2LouderEngineSound#3]
This is a cool project. For exacting the audio files, you had mentioned in the OutRun2006Tweaks thread that you used a not yet public version of game extractor. It still looks like they haven't added support for the OR2 pak files into the public version, so I was wondering if you could provide a copy of all the game's sounds extracted.
I'm not looking to edit or re-package them, just would like to take a listen though to hear any cut or different content. (I was able to import them in Audacity but it's kind of clunky). No worries if not.

**Comment by ksdomino** [comment]
If you can please email watto and ask for the version that supports extraction of outrun 2 files they will be more than happy to send it to you (because it could lead to a potential sale for them). It's a bit tricky for me to access the extracted files at the moment as I'm on a mac and my pc isn't easily accessible and my poor organisation skills meant whatever files I did extract -probably not the full set but enough to get this project done - are a bit tricky to get to.

**Comment by thegreatprophetzarquon** [comment]
Sounds good, thank you!
